-- ============================================================================
-- BANCO BANQUITO V2 - CORE ADMIN SERVICE
-- Modelo fisico MySQL 8.4 LTS
-- Base: banquito_core_admin_db
-- Proposito: configuracion bancaria, sucursales, feriados, ventanas operativas,
-- catalogos de cuenta/transaccion, instituciones financieras y perfiles internos.
-- El tarifario de pagos masivos NO vive en Core; pertenece a Switch Facturacion.
-- ============================================================================
CREATE TABLE IF NOT EXISTS SUCURSAL (
  ID INT AUTO_INCREMENT NOT NULL,
  UUID_SUCURSAL CHAR(36) NOT NULL,
  CODIGO_SUCURSAL VARCHAR(10) NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  CIUDAD VARCHAR(80) NOT NULL,
  DIRECCION VARCHAR(300) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_SUCURSAL PRIMARY KEY (ID),
  CONSTRAINT UK_SUCURSAL_UUID UNIQUE (UUID_SUCURSAL),
  CONSTRAINT UK_SUCURSAL_CODIGO UNIQUE (CODIGO_SUCURSAL),
  CONSTRAINT CK_SUCURSAL_ESTADO CHECK (ESTADO IN ('ACTIVA','INACTIVA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sucursales Banco BanQuito';

CREATE TABLE IF NOT EXISTS FERIADO (
  FECHA_FERIADO DATE NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  ES_FIN_SEMANA TINYINT(1) NOT NULL DEFAULT 0,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_FERIADO PRIMARY KEY (FECHA_FERIADO),
  CONSTRAINT CK_FERIADO_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Calendario de dias no habiles';

CREATE TABLE IF NOT EXISTS PARAMETRO_CORE (
  CODIGO VARCHAR(60) NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  VALOR_TEXTO VARCHAR(300) NOT NULL,
  TIPO_DATO VARCHAR(20) NOT NULL DEFAULT 'STRING',
  DESCRIPCION VARCHAR(500) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_PARAMETRO_CORE PRIMARY KEY (CODIGO),
  CONSTRAINT CK_PARAM_CORE_TIPO CHECK (TIPO_DATO IN ('STRING','INTEGER','DECIMAL','BOOLEAN','TIME','JSON')),
  CONSTRAINT CK_PARAM_CORE_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Parametros funcionales del Core';

CREATE TABLE IF NOT EXISTS VENTANA_OPERATIVA (
  ID INT AUTO_INCREMENT NOT NULL,
  CODIGO VARCHAR(50) NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  DOMINIO_OPERATIVO VARCHAR(30) NOT NULL COMMENT 'CORE, SWITCH, CANAL, SFTP, CONTABLE',
  HORA_INICIO TIME NOT NULL,
  HORA_CORTE TIME NOT NULL,
  HORA_FIN TIME NOT NULL,
  DIAS_APLICA VARCHAR(50) NOT NULL DEFAULT 'LUN,MAR,MIE,JUE,VIE',
  TIMEZONE VARCHAR(60) NOT NULL DEFAULT 'America/Guayaquil',
  ACCION_DESPUES_CORTE VARCHAR(30) NOT NULL DEFAULT 'SIGUIENTE_DIA_HABIL',
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_VENTANA_OPERATIVA PRIMARY KEY (ID),
  CONSTRAINT UK_VENTANA_OPERATIVA_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_VENTANA_DOMINIO CHECK (DOMINIO_OPERATIVO IN ('CORE','SWITCH','CANAL','SFTP','CONTABLE')),
  CONSTRAINT CK_VENTANA_ACCION CHECK (ACCION_DESPUES_CORTE IN ('RECHAZAR','ENCOLAR','SIGUIENTE_DIA_HABIL','PERMITIR')),
  CONSTRAINT CK_VENTANA_ESTADO CHECK (ESTADO IN ('ACTIVA','INACTIVA')),
  CONSTRAINT CK_VENTANA_HORAS CHECK (HORA_INICIO <= HORA_CORTE AND HORA_CORTE <= HORA_FIN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Ventanas operativas y horarios de corte';

CREATE TABLE IF NOT EXISTS INSTITUCION_FINANCIERA (
  ID INT AUTO_INCREMENT NOT NULL,
  ROUTING_CODE VARCHAR(20) NOT NULL,
  NOMBRE VARCHAR(150) NOT NULL,
  ES_BANQUITO TINYINT(1) NOT NULL DEFAULT 0,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_INSTITUCION_FINANCIERA PRIMARY KEY (ID),
  CONSTRAINT UK_IF_ROUTING UNIQUE (ROUTING_CODE),
  CONSTRAINT CK_IF_ESTADO CHECK (ESTADO IN ('ACTIVA','INACTIVA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Catalogo de instituciones financieras';

CREATE TABLE IF NOT EXISTS SUBTIPO_CUENTA (
  ID INT AUTO_INCREMENT NOT NULL,
  CODIGO VARCHAR(30) NOT NULL,
  TIPO_BASE VARCHAR(15) NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION VARCHAR(300) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_SUBTIPO_CUENTA PRIMARY KEY (ID),
  CONSTRAINT UK_SUBTIPO_CUENTA_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_SUBTIPO_CUENTA_BASE CHECK (TIPO_BASE IN ('AHORROS','CORRIENTE','NOMINA')),
  CONSTRAINT CK_SUBTIPO_CUENTA_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Catalogo de productos de cuenta';

CREATE TABLE IF NOT EXISTS SUBTIPO_TRANSACCION (
  ID INT AUTO_INCREMENT NOT NULL,
  CODIGO VARCHAR(40) NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  TIPO_MOVIMIENTO_BASE VARCHAR(10) NOT NULL,
  DESCRIPCION VARCHAR(300) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_SUBTIPO_TRANSACCION PRIMARY KEY (ID),
  CONSTRAINT UK_SUBTIPO_TRANSACCION_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_SUBTIPO_TRANSACCION_BASE CHECK (TIPO_MOVIMIENTO_BASE IN ('DEBITO','CREDITO')),
  CONSTRAINT CK_SUBTIPO_TRANSACCION_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Catalogo de subtipos de transaccion';

CREATE TABLE IF NOT EXISTS USUARIO_CORE (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_USUARIO_CORE CHAR(36) NOT NULL,
  UUID_IDENTIDAD CHAR(36) NOT NULL COMMENT 'Referencia a identity-access-service; no password aqui',
  CODIGO_SUCURSAL VARCHAR(10) NULL COMMENT 'Sucursal operativa; sin FK cruzada hacia servicios consumidores',
  NOMBRE_COMPLETO VARCHAR(160) NOT NULL,
  CARGO VARCHAR(100) NULL,
  ESTADO_OPERATIVO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_USUARIO_CORE PRIMARY KEY (ID),
  CONSTRAINT UK_USUARIO_CORE_UUID UNIQUE (UUID_USUARIO_CORE),
  CONSTRAINT UK_USUARIO_CORE_IDENTIDAD UNIQUE (UUID_IDENTIDAD),
  CONSTRAINT CK_USUARIO_CORE_ESTADO CHECK (ESTADO_OPERATIVO IN ('ACTIVO','INACTIVO','SUSPENDIDO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Perfil operativo de empleados del banco';

CREATE TABLE IF NOT EXISTS AUDITORIA_ADMIN_EVENTO (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  UUID_USUARIO CHAR(36) NULL,
  MODULO VARCHAR(60) NOT NULL,
  ACCION VARCHAR(80) NOT NULL,
  ENTIDAD VARCHAR(80) NOT NULL,
  ENTIDAD_ID VARCHAR(80) NULL,
  RESULTADO VARCHAR(15) NOT NULL,
  DETALLE_JSON JSON NULL,
  FECHA_EVENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_AUDITORIA_ADMIN PRIMARY KEY (ID),
  CONSTRAINT CK_AUDITORIA_ADMIN_RESULTADO CHECK (RESULTADO IN ('OK','ERROR','DENEGADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Auditoria local de admin-service';

CREATE TABLE IF NOT EXISTS OUTBOX_EVENT (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_EVENTO CHAR(36) NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  TIPO_EVENTO VARCHAR(80) NOT NULL,
  AGREGADO_TIPO VARCHAR(80) NOT NULL,
  AGREGADO_ID VARCHAR(80) NOT NULL,
  PAYLOAD_JSON JSON NOT NULL,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  INTENTOS INT NOT NULL DEFAULT 0,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_PUBLICACION DATETIME NULL,
  ERROR_ULTIMO VARCHAR(1000) NULL,
  CONSTRAINT PK_OUTBOX_ADMIN PRIMARY KEY (ID),
  CONSTRAINT UK_OUTBOX_ADMIN_UUID UNIQUE (UUID_EVENTO),
  CONSTRAINT CK_OUTBOX_ADMIN_ESTADO CHECK (ESTADO IN ('PENDIENTE','PUBLICADO','ERROR','DESCARTADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Eventos confiables del admin-service';

CREATE INDEX IDX_USUARIO_CORE_IDENTIDAD ON USUARIO_CORE(UUID_IDENTIDAD);
CREATE INDEX IDX_VENTANA_DOMINIO ON VENTANA_OPERATIVA(DOMINIO_OPERATIVO, ESTADO);
CREATE INDEX IDX_OUTBOX_ADMIN_ESTADO ON OUTBOX_EVENT(ESTADO, FECHA_CREACION);
