-- R9-K.1: metadatos de enrutamiento para clasificación y validación Off-Us.
-- Cambio aditivo: no altera contratos On-Us ni migraciones anteriores.

DELIMITER $$

DROP PROCEDURE IF EXISTS align_r9k_interbank_routing_metadata$$
CREATE PROCEDURE align_r9k_interbank_routing_metadata()
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'INSTITUCION_FINANCIERA'
           AND COLUMN_NAME = 'PREFIJO_CUENTA'
    ) THEN
        ALTER TABLE INSTITUCION_FINANCIERA
            ADD COLUMN PREFIJO_CUENTA VARCHAR(10) NULL
            AFTER NOMBRE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.STATISTICS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'INSTITUCION_FINANCIERA'
           AND INDEX_NAME = 'UK_INSTITUCION_PREFIJO_CUENTA'
    ) THEN
        CREATE UNIQUE INDEX UK_INSTITUCION_PREFIJO_CUENTA
            ON INSTITUCION_FINANCIERA (PREFIJO_CUENTA);
    END IF;
END$$

CALL align_r9k_interbank_routing_metadata()$$
DROP PROCEDURE align_r9k_interbank_routing_metadata$$

DELIMITER ;

UPDATE INSTITUCION_FINANCIERA
   SET PREFIJO_CUENTA = '20202'
 WHERE ROUTING_CODE = 'BQTO001'
   AND (PREFIJO_CUENTA IS NULL OR PREFIJO_CUENTA = '');

INSERT INTO INSTITUCION_FINANCIERA
    (ROUTING_CODE, NOMBRE, PREFIJO_CUENTA, ES_BANQUITO, ESTADO)
VALUES
    ('BQLL001', 'Banco BanQuill', '10101', 0, 'ACTIVA')
ON DUPLICATE KEY UPDATE
    NOMBRE = VALUES(NOMBRE),
    PREFIJO_CUENTA = VALUES(PREFIJO_CUENTA),
    ES_BANQUITO = VALUES(ES_BANQUITO),
    ESTADO = VALUES(ESTADO);

INSERT INTO SUBTIPO_TRANSACCION
    (CODIGO, NOMBRE, TIPO_MOVIMIENTO_BASE, DESCRIPCION, ESTADO)
VALUES
    ('PAGO_OFFUS_RECIBIDO', 'Pago interbancario recibido', 'CREDITO',
     'Crédito a beneficiario local por transferencia Off-Us entrante', 'ACTIVO')
ON DUPLICATE KEY UPDATE
    NOMBRE = VALUES(NOMBRE),
    TIPO_MOVIMIENTO_BASE = VALUES(TIPO_MOVIMIENTO_BASE),
    DESCRIPCION = VALUES(DESCRIPCION),
    ESTADO = VALUES(ESTADO);
